// Snoop design tokens — single palette only (cream / peach / blue)
export const theme = {
  colors: {
    bg1: '#FAFAF7',
    bg2: '#FFEBCC',
    surface: '#FFF9D2',
    accent: '#8CC0EB',
    accentDeep: '#4A90C7',
    accentInk: '#1E2B4D',
    accentSoft: 'rgba(140, 192, 235, 0.28)',
    savings: '#3FA66B',
    savingsSoft: 'rgba(63, 166, 107, 0.15)',
    text1: '#1E2B4D',
    text2: '#6F7480',
    divider: '#EAE6D8',
    error: '#E07A5F',
    navy: '#0D0B61',
    character: '#FFFFFF',
    characterInk: '#1E2B4D',
    white: '#FFFFFF',
  },
  spacing: {
    s1: 4,
    s2: 8,
    s3: 12,
    s4: 16,
    s5: 20,
    s6: 24,
    s8: 32,
    s10: 40,
    s12: 48,
  },
  radius: {
    chip: 8,
    compact: 12,
    card: 16,
    nav: 24,
    pill: 999,
  },
  // iOS Human Interface Guidelines type scale
  typography: {
    display: { fontSize: 34, fontWeight: '700' as const, letterSpacing: -0.4 },
    title1: { fontSize: 28, fontWeight: '700' as const, letterSpacing: -0.3 },
    title2: { fontSize: 22, fontWeight: '700' as const, letterSpacing: -0.26 },
    title3: { fontSize: 20, fontWeight: '600' as const, letterSpacing: -0.24 },
    headline: { fontSize: 17, fontWeight: '600' as const, letterSpacing: -0.08 },
    body: { fontSize: 17, fontWeight: '400' as const, letterSpacing: -0.08 },
    callout: { fontSize: 16, fontWeight: '400' as const, letterSpacing: -0.06 },
    subheadline: { fontSize: 15, fontWeight: '400' as const, letterSpacing: -0.04 },
    footnote: { fontSize: 13, fontWeight: '400' as const, letterSpacing: 0 },
    caption: { fontSize: 12, fontWeight: '400' as const, letterSpacing: 0 },
  },
  shadows: {
    rest: {
      shadowColor: '#1E2B4D',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 4,
      elevation: 2,
    },
    card: {
      shadowColor: '#1E2B4D',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.10,
      shadowRadius: 12,
      elevation: 4,
    },
    floating: {
      shadowColor: '#1E2B4D',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.22,
      shadowRadius: 24,
      elevation: 16,
    },
    nav: {
      shadowColor: '#0D0B61',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.30,
      shadowRadius: 20,
      elevation: 20,
    },
  },
} as const;
